---
- name: launch vm for worker2 node
  os_server:
    state: present
    auth:
      auth_url: "{{ openstack_url }}"
      username: "{{ openstack_username }}"
      password: "{{ openstack_password }}"
      project_name: "{{ openstack_project }}"
    name: "{{ instance_worker2_name }}"
    image:  "{{ instance_worker2_image }}"
    flavor:  "{{ instance_worker2_flavor }}"
    security_groups: "{{ security_group }}"
    timeout: 3600
    auto_ip: yes
#    volumes: "{{ instance_worker2_volume }}"
    volumes: "{{ worker2_volume.id }}"
    nics:
      - net-id: "{{ nic }}"
  register: worker2_ip
